# Generated by Django 6.0.2 on 2026-02-03 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("year", models.CharField(blank=True, max_length=50, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("image_url", models.URLField(max_length=500)),
                ("audio_url", models.URLField(blank=True, max_length=500, null=True)),
                ("user_consented", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("user_id", models.CharField(default="anonymous", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Story",
                "verbose_name_plural": "Stories",
                "ordering": ["-created_at"],
            },
        ),
    ]
