# Generated by Django 6.0.2 on 2026-03-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["is_public", "user_consented", "-created_at"],
                name="gallery_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(fields=["-created_at"], name="created_at_idx"),
        ),
    ]
