# Generated by Django 6.0.2 on 2026-03-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_gallery_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="story",
            name="gallery_idx",
        ),
        migrations.AddField(
            model_name="story",
            name="requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="Story requires moderator approval before appearing in public gallery",
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=[
                    "is_public",
                    "user_consented",
                    "requires_approval",
                    "-created_at",
                ],
                name="gallery_idx",
            ),
        ),
    ]
